### PR TITLE
Reduce the memory footprint

### PR DESCRIPTION
**Pull request by tobozo**
[edit] see #36

youpi I have succeeded into dropping TFT_eSPI from ESP32Marauder, now it's compiling and running fine on my custom LoLinD32Pro + ILI9341 build

The sketch now compiles using the default partition size, more SPIFFS space \o/

image

there was a tradeoff though, probably not an issue on other builds, but I had to remove the SD Card from the slot in order to get the display correctly detected, while this may be isolated to my situation there's still a solution for that, so let me know if this happens to you too (symptom : LoLinD32Pro is detected as M5Stack)

SD support, battery/neopixel and other stuff I don't have on my build have been disabled in the setup(), feel free to re-enable them, but only after testing :-)

https://github.com/tobozo/ESP32Marauder-1/commit/a5d93179e8bc9b562e82f133b6eda1ba45b5f5a0 

## requirements : 

1) use the very latest version of LovyanGFX you can find in the Arduino Library Manager
2) use the "[Touch](https://github.com/tobozo/ESP32-Chimera-Core/tree/Touch)" branch of ESP32-Chimera-Core
3) select the "LoLinD32Pro" from the boards menu when compiling

### CODE REVIEW

**Comment by justcallmekoko** [comment]
I am having a hard time getting anything to display. Just a white screen so far

**Comment by tobozo** [comment]
what does the serial output say when you compile with "warning" log_level ?

**Comment by justcallmekoko** [comment]
it says detect fail

**Comment by justcallmekoko** [comment]
Yea I am still having issues with getting the display to work. I changed the pins in LVGX to match my schematic but it still did not work

**Comment by justcallmekoko** [comment]
@tobozo  So I got it working after defining the board as wrover kit instead of d32 pro.
I tried out some of the functions.

You were right that this thing will not work with SD card. Even if you boot it without an SD card, the screen immediately stops working if you plug in the SD card after boot.

The scrolling screen during the sniffers is messing with the fonts quite a bit which cases the text not to line up properly.

Opening functions like the packet monitor then exiting back to the menu cause the fonts to act weird as well.

I will post pictures when I can.

**Comment by kevinjreeder** [comment]
Thanks

**Pull request merged**
