### PR TITLE
Joshinken better logo

### PR DESCRIPTION
**Pull request by Joshinken**
upscaled the logo

### CODE REVIEW

**Comment by Joshinken** [comment]
didnt even change any code, leave me alone travis

**Comment by tobozo** [comment]
@Joshinken see #28

**Comment by Joshinken** [comment]
@tobozo i know, i just didnt think to implement that in here

**Comment by justcallmekoko** [comment]
Why is it showing changes made to display? The changes look the same as the previous pull

**Comment by Joshinken** [comment]
@justcallmekoko no idea

**Comment by tobozo** [comment]
<p float="left">

image image

</p>

**Comment by Joshinken** [comment]
yeah i just upscaled the logo using waifu2x

**Pull request closed without merging**
