### PR TITLE
ESP32-S3 SD card fixes & buffer changes

### PR DESCRIPTION
**Pull request by fOmey**
Modified the SD card library to use the SD_MMC.

Pin definitions will need to modified.. including flipper (only added as template, I don't own any currently officially supported devices).

---

Dynamically allocate & free buffer memory when needed, this eliminates dropped packets entirely on a ESP32-S3 (not tested on a ESP32).

---

broadcastCustomBeacon malformed packet fix.

### CODE REVIEW

**Comment by SomeToms64** [comment]
Works, but needs a pinout code change in configs.h to work with the Bork multiboard.

**Comment by SomeToms64** [comment]
Will test with the s2

**Comment by justcallmekoko** [comment]
What configurations have you tested?

**Comment by justcallmekoko** [comment]
Also having a small problem in the workflow of your fork [here](https://github.com/justcallmekoko/ESP32Marauder/actions/runs/5063427431/jobs/9216729473#step:17:368).

It's complaining about SD_MMC not being declared. SD_MMC is already included in the arduino-esp32 core so not sure what the deal is here yet. See if you can get the workflow running properly so you can start checking to see if everything else still compiles for the other boards.

**Comment by fOmey** [comment]
Seems to compile fine locally, not sure why SD_MMC is out of scope. Going to nuke the fork and start fresh as a sanity check.

**Pull request closed without merging**
