### PR TITLE
Disable rgb led option

### PR DESCRIPTION
**Pull request by eried**
Solves bootloop on some boards with limited pins, like https://github.com/justcallmekoko/ESP32Marauder/issues/205

### CODE REVIEW

**Comment by TQMatvey** [comment]
would love to see this being merged, as any third party esp32 boards used with flipper zero will crash if you dont remove RGB LED reference, this indeed work.

**Comment by sfjuocekr** [comment]
I think this can be refactored to having a HAS_LED define, which will then be complemented by a define for what LED it uses?

I was looking at porting some of the ESP32CAM changes over the other day and the SDInterface needs such a refactor as well to include SD_MMC.

**Comment by sfjuocekr** [comment]
I created a PR with what I think is a better solution to the LED problem.

**Comment by eried** [comment]
> I think this can be refactored to having a HAS_LED define, which will then be complemented by a define for what LED it uses?
> 
> I was looking at porting some of the ESP32CAM changes over the other day and the SDInterface needs such a refactor as well to include SD_MMC.

Yes! Please implement 😁 https://github.com/eried/flipperzero-mayhem/ I added sd_mmc but not very elegantly

**Pull request closed without merging**
