### PR TITLE
adapted write_packets_serial pins for esp32-wroom-32

### PR DESCRIPTION
**Pull request by coded-with-claws**
Hi,
I propose this change for #249 :)
Of course, after testing, the lines must be commented out as default configuration.

### CODE REVIEW

**Comment by DokuPP** [comment]
Is this working in the version 13.5 of marauder?

**Comment by coded-with-claws** [comment]
Hmmm, no, on 0.13.5 I now have an error related to SD card.

**Comment by Willy-JL** [comment]
#452 will make this unnecessary, serial pcaps will work on all boards, without need of a secon serial.

**Comment by coded-with-claws** [comment]
Like @Willy-JL said, we no longer need a second serial thanks to unified pcap saving

**Pull request closed without merging**
