### PR TITLE
nyeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee2

### PR DESCRIPTION
**Pull request by Joshinken**
just imagine more e's here

### CODE REVIEW

**Comment by justcallmekoko** [comment]
Did you happen to test this to find out how much RAM you have available while having an SD card inserted?

**Comment by Joshinken** [comment]
i have not checked, but my model stays above 130000bytes even with an sd card, however, since the official esp marauder hardware doesnt need this battery check, i can change the code to not create any new variables while inactive (the total ram usage right now while active should only be 26 bytes anyways)

i need to make a minor adjustment to the code anyways to make it display the battery value immediately, because, as it is right now, it only shows the battery value after the banner updates 50 times

**Comment by Joshinken** [comment]
well i say i "need to make an adjustment", i already did, i just need to commit it

**Comment by justcallmekoko** [comment]
Yea if you don't mind adding that extra snippet for the variable creation depending on battery mode like you were talking about.
Could you also implement the same check for setting the pin mode of the pins used for the battery?

**Comment by Joshinken** [comment]
eeeeeeeeeeeeeeeh

probably? i think i need to move the definition to the .h file then tho, and then i need to reqwrite the readme, and them ill probably be here for 8 hours because something somewhere has gone wrong

**Pull request closed without merging**
