### PR TITLE
Joshinken patch analog battery

### PR DESCRIPTION
**Pull request by Joshinken**
OH MY HOT DIGGETY IM GETTING ANNOYED BY THIS

TURNS OUT IT CAN RETURN BATTERY VALUES OF LESS THAN 0%, SO I HAD TO PUT IN CODE FOR THAT LITTLE EVENTUALITY

its 2am, i just wanna go to bed

### CODE REVIEW

**Comment by justcallmekoko** [comment]
So for some reason your changes aren't being marked properly. It shows your deletions are pretty much entire files, but your additions are putting the same lines of code back. It is making it difficult to find your actual code changes.

I see some of the changes you made, but it's marking code that had already been there as additions.

Are you still having issues getting accurate battery level readings with this method?

**Comment by tobozo** [comment]
see the [real diff](https://github.com/justcallmekoko/ESP32Marauder/pull/31/files?diff=unified&w=1)

image

**Comment by Joshinken** [comment]
I am getting reading, though their accuracy is questionable. I wouldnt bet my house on the readings, but its more accurate than guessing how much battery is left. This code should be made more reliable with the use of a capacitor

**Comment by Joshinken** [comment]
I can take several samples of the battery at the same time, calculate an average, and throw out values that deviate too much from that average to massively increase the reliability of this method, at the cost of creating a bunch of new variables. Shouldnt use up too much ram in the grand scheme of things, but, y’know

**Comment by justcallmekoko** [comment]
Well since this is your hardware mod, I'll trust whatever you think will give you the best bang for your buck in terms of free space vs. results.

Any reason for removing the RAM usage from the status bar?

**Comment by Joshinken** [comment]
There was ram usage on the status bar?

I didnt remove anything, soooo

**Comment by justcallmekoko** [comment]
I just checked and it's pretty awesome that github doesn't show this info right on the pull request but your branch is 4 commits behind master and it is missing the RAM usage snippet for the status bar.

**Comment by Joshinken** [comment]
It did tell me i was behind the master, but this branches directly off the master, so i dont know why.

I also dont remember there being a ram usage bar when i first set up my marauder, is it a new thing?

**Comment by justcallmekoko** [comment]
It's pretty new. I added it on the 9th.

**Comment by Joshinken** [comment]
i think i made my own branch when i did the drawing function and now im stuck on that, and that why im now behind the master

**Comment by justcallmekoko** [comment]
But the drawing branch was up to date with the commit that had the status bar changes

**Comment by Joshinken** [comment]
and i say that because according to the master i use, this project is mine, and that doesnt feel right

**Comment by Joshinken** [comment]
i dont know. ill just try to stay on the master from now on and get my changes up to date.

btw, is it ok if i just include the upscaled logo in my commit?

**Comment by justcallmekoko** [comment]
I would like to have both logos included in the project

**Comment by Joshinken** [comment]
should i add some code so you can switch the logo?

**Comment by Joshinken** [comment]
THE MASTER BRANCH FLIPS MY TOUCHSCREEN; HEPL

**Comment by justcallmekoko** [comment]
If you touch is slipped, make sure you change the defines [here](https://github.com/justcallmekoko/ESP32Marauder/blob/master/esp32_marauder/Display.h#L18)...if that's what you're talking about

**Comment by Joshinken** [comment]
the battery code no longer works on the newest master, and i have absolutely no idea why

**Comment by justcallmekoko** [comment]
What is the result?

**Comment by Joshinken** [comment]
literally nothing, it does not show the any percentage or even the battery symbol

**Comment by Joshinken** [comment]
something draws over the battery percentage meter, so it doesnt show up unless i refresh it every loop, which makes it flicker

**Comment by tobozo** [comment]
touchscreen flip => check your display rotation value

**Comment by justcallmekoko** [comment]
Would you be able to show pictures of what it looked like while working and what it looks like now?

Would it also be possible to only update the battery percentage when it detects a change in the percentage. 
It would cut down on the flickering. That is what I had to do for the other values on the status bar.

**Comment by Joshinken** [comment]
FUCK NO IT DOESNT GET UPDATED BECAUSE THE REPORTED VALUE IS 0; BECAUSE MY BATTERY IS DEAD; BECAUSE I LEFT MY MARAUDER RUNNING OVER NIGHT TO TESTS THE CODE; SO IT CHECKS IF THE VALUE IS DIFFERENT TO THE LAST VALUE; THE LAST VALUE DEFAULTS TO 0; IT DETECTS THE CURRENT VALUE AS 0; 0 IS EQUAL TO 0; THE CODE DOESNT UPDATE

**Comment by Joshinken** [comment]
also, checking the battery with a multimeter, its at 3.4v, so it should be empty yet???

**Comment by justcallmekoko** [comment]
Sorry I am not retaining info today. Got a lot of stuff going on at once. Now I am all caught up with the flicker and not updating and overwriting.

What I would recommend if it is still being overwritten is to modify the size of the rectangle from the other values on the status bar that keeps running over your battery percentage.

**Comment by tobozo** [comment]
@Joshinken here's a fix for your keyboard :rofl: 

image

**Comment by Joshinken** [comment]
oh my god i found the issue.

one line of code. 

one line of code i forgot i wrote

right in the .ino file
"  pinMode(BATTERY_PIN, OUTPUT);"

the mosfet was never turned on, so the adc was always grounded, so it always read 0

im gonna walk into the ocean now

**Comment by Joshinken** [comment]
also @tobozo i actually hold down down the shift key when im yelling, which is weird for someone who used to press caps, type the letter they need, and then press caps again, every time they wanted a single capitalized letter.

**Pull request closed without merging**
