### PR TITLE
Unified serial PCAPs

### PR DESCRIPTION
**Pull request by Willy-JL**
### Main objectives:
- Serial PCAPs and logs are sent on main console UART:
  - Text output and buffer data separated by using `[BUF/BEGIN]` and `[BUF/CLOSE]` markers
  - This is enabled via a CLI `-serial` option, no need for separate .bin's anymore
  - Ignoring/filtering the markers handled by application layer (eg. Flipper Zero Marauder Companion app)
  - Without `-serial` flag everything behaves as before, users won't notice a difference
- Not needing a second serial means:
  - All boards support serial PCAPs/logs, not just ESP32-S2 / Flipper WiFi Module
  - Second serial can be used for GPS
  - No interference with SD card, can save to both SD card and serial at same time

### Technical details:
- fe08c145f6467cde0a7d80851e466af80872f6ed I noticed everywhere else `do_save` was used to toggle the calls to `addLog()`, while here it was set but `addLog()` was always called, fixed it
- d0f5d89980d6d155a467f74fc543594b68835597 Instead `do_save` on `SDInterface` was a remnant from 4 years ago, set to true and never toggled, removed since it was redundant
- Fully reworked pcap/log capture system to be centralized and streamlined into `buffer_obj`, supporting both sd and serial together:
  - f6c27ed2167f67054b2212c1b82eb62eeffe3f6d For adding capture data, also simplifies log data conversion (type casting instead of redundant copying), later changed to a single append() overloaded function in 9d92c5ceb5d42b26937e326a046b56c511e0fea6
  - c61aaf95cd06d4f9ecb5ab2f641422e4fa72d834 For opening captures, remembers the filesystem and serial boolean passed for saving later on, also adds more return guards for valid GPS state
  - 2004a9ecb4e90a667300d991c5d6881befa64b0d For saving capture data to file and/or serial as chosen when opening
  - e560a888c30fcbc3ca79c0794231fdf2bac65612 Makes sure buffer doesnt change while saving, writes will wait
- bddc7e1d9d44f785bb1c39b90ab49242de390410 Main point of the PR, serial PCAPs and logs are sent on main UART between `[BUF/BEGIN]` and `[BUF/CLOSE]` markers, removes `WRITE_PACKETS_SERIAL` restrictions in the whole project since second serial is not an issue anymore, and also the related `configs.h` variables that are left unused
- 558fe18d66481fabd7407d87ed9a7c1db933b9fe Replaces the `WRITE_PACKETS_SERIAL` config with a `-serial` commandline option for all scan/attack commands, no need for a second bin anymore

### Example:
What happens:
```
#sniffpmkid -serial
Starting PMKID sniff on channel 1. Stop with stopscan
>[BUF/BEGIN]bla
bla
network traffic[BUF/CLOSE]Received EAPOL:
00:00:00:00:00:00
[BUF/BEGIN]bla
bla
pcap go
very brrrr[BUF/CLOSE]Received EAPOL:
00:00:00:00:00:00
```

What the user sees with companion app filtering the markers:
```
#sniffpmkid -serial
Starting PMKID sniff on channel 1. Stop with stopscan
>Received EAPOL:
00:00:00:00:00:00
Received EAPOL:
00:00:00:00:00:00
```

What the companion app saves into the pcap:
```
bla
bla
network trafficbla
bla
pcap go
very brrrr
```

### Notes:
I had already implemented this about a month ago but with no CLI toggle, it always dumped into serial. That is currently bundled with the latest (v52) release of Xtreme Flipper Zero firmware, along with a modified companion app that handles the markers and dumps to pcap file (see [here](https://github.com/Flipper-XFW/Xtreme-Apps/blob/dev/wifi_marauder_companion/wifi_marauder_uart.c#L51-L104)).

The big concensus is that this is the easiest and most hassle free way to handle serial PCAPs, since it works for all boards and doesnt require fiddling with bins and UARTs. Safe to say this marker method works well and so I decided to improve it and make it easily togglable, which required a deep rework of the `buffer_obj` and capture system, although it's probably for the best since the previous setup was a bit spaghetti-sh.

I already verified the serial part to be working as intended, PCAPs land into Flipper storage with no problems. I don't have a board with SD card at hand at the moment to double check this new rework, but I am confident that it should be working as intended, saving to SD card when possible and to serial when set as commandline option.

I will be making a pull request to @0xchocolate 's official companion app to add support for this very shortly.

### CODE REVIEW

**Comment by Willy-JL** [comment]
Actually just thought that the pcapAdd and logAdd can be simplified into a single append() function that works with overloads... I'll do that super quick, and also merge develop branch

**Comment by Willy-JL** [comment]
Made the worklow run on pull request synchronize too (pull_request event does opened, synchronize, reopened by default) so new builds are made when PR is updated (was not building after I pushed my new changes)

**Comment by justcallmekoko** [comment]
@Willy-JL been super busy but I will start testing this with my devices soon. Before I do that, would you mind resolving the MR conflicts? I had added some GPS module stuff to make sure the user has control over the power of the GPS module

**Comment by Willy-JL** [comment]
that should do it

**Comment by justcallmekoko** [comment]
@Willy-JL Thank you for the very comprehensive write-up. I will start testing this and I look forward to merging this once complete. Really awesome work here!

**Comment by Willy-JL** [comment]
@justcallmekoko any rumors on when the next release might roughly be? Just to have an idea of when the app and tutorials would need to be updated for this change

**Pull request merged**
